"""add user display/accessibility prefs

Revision ID: f58c3113f516
Revises: 9f468e4961f3
Create Date: 2026-07-07 15:08:26.011054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58c3113f516'
down_revision = '9f468e4961f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_size', sa.String(length=10), server_default='normal', nullable=False))
        batch_op.add_column(sa.Column('high_contrast', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('high_contrast')
        batch_op.drop_column('text_size')

    # ### end Alembic commands ###
